#!/usr/bin/env bash

latest_version=$(curl -s 'https://api.github.com/repos/nvm-sh/nvm/releases/latest' | \
    python3 -c "import sys, json; print(json.load(sys.stdin)['tag_name'])")

echo Installing version $latest_version

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$latest_version/install.sh | bash
